# Generated by Django 6.0 on 2025-12-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="caption",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
