# Generated by Django 6.0 on 2025-12-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_granted',
            field=models.BooleanField(default=False),
        ),
    ]
